### ISSUE TITLE
App frontend crashes when deleting a row in repeating group while a server error has been triggered on a different component

### ISSUE THREAD

**Issue by ingunnjv** [Altinn/app-frontend-react#139] opened 2022-02-15 11:11 UTC
## Description
When I try to delete a row in a repeating group in a special case, the app crashes with "Ukjent feil". On page reload, the row has been deleted.
The 'special case' is that a custom server validation has been triggered on a different field on the same page before trying to delete a row. When no such custom validation has been triggered, deletion works as expected.

## To Reproduce
Occurs in oko/mt-3 in TT02 and locally
1. Open an instance of oko/mt-3
2. Make the following choices on the first page: ![image](https://user-images.githubusercontent.com/25951311/154047815-f817b7f2-7321-49d9-86fe-71c1f395df01.png)
3. Click on 'Neste' twice until you reach the page with header 'Mistanken'.
4. Choose 'Ja' in 'Referere til tidligere meldinger?'
5. Add at least one row in the repeating group that appears
6. Fill in dates in the fields 'Periode - Fra (ca)' and 'Til (ca)':
- 'Periode - Fra (ca)' should be a later date than 'Til (ca)' to trigger a custom server validation.
- See that the two fields are marked with errors:
![image](https://user-images.githubusercontent.com/25951311/154048844-c4b47eca-ccda-4bf6-939f-3dbb87933242.png)

7. Delete a row from the repeating group
8. Results in 'Ukjent feil'
9.  When reloading from the error page, we see that the row was/appears to be deleted 

## Expected behavior
The row is deleted without error.

## Additional info
Browser: chrome
Where: tt02 and locally
App example: oko/mt-3

**Comment by lorang92** [comment] 2022-08-17 08:21
Duplicate of #371, closing.

**Closed by lorang92** 2022-08-17 08:21 UTC
Labels: kind/bug, solution/app-frontend, org/pod
