### ISSUE TITLE
Required message not removed when no longer required

### ISSUE THREAD

**Issue by MagnusMolaugFinans** [Altinn/app-frontend-react#1941] opened 2024-02-08 09:13 UTC
### Description of the bug

If a field is set to required but has a dynamic expression that can make it not required anymore, the validation error message is not removed despite it being not required. 

### Steps To Reproduce

1. have a required field with the required being a dynamic expression dependent on another component
2. trigger validation and make the required validation error message appear
3. make the field no longer required by changing the value of the other component

### Additional Information

![image](https://github.com/Altinn/altinn-studio/assets/133201484/4a9821dd-39a8-4d3e-977e-aa60d4f06c3e)
![image](https://github.com/Altinn/altinn-studio/assets/133201484/8fc01356-ed8f-4da7-a8b1-a597c475f756)
see that in the second screenshot the component is no longer required

**Comment by olemartinorg** [comment] 2024-03-18 10:28
Seems to be a duplicate of #1156.

I tested upgrading the app to v8/v4 now, and the bug is fixed there. Would it be possible to upgrade this app to v4/v8, @MagnusMolaugFinans?

**Comment by olemartinorg** [comment] 2024-03-25 10:31
Closing this as done, and as a duplicate of #1156.

**Closed by olemartinorg** 2024-03-25 10:31 UTC
Labels: kind/bug, area/validation, needs-info, spring-cleaned
