### ISSUE TITLE
Add displayValue function to Expressions.

### ISSUE THREAD

**Issue by framitdavid** [Altinn/app-frontend-react#1208] opened 2023-05-30 09:44 UTC
Looks up a component nearby, and presents its display value (which should work for number-formatted Input fields). See comment here: https://github.com/Altinn/app-frontend-react/issues/1105#issuecomment-1536240868

We cannot use the **useDisplayData** method on the component directly within the expressions functions. This is primarily because **useDisplayData** may rely on hooks, causing React to crash if the number of hooks doesn't align with the previous render.

We need to figure out a solution for accessing the same data on the components without using hooks. I hope we can avoid implementing the same logic twice, with/out hooks.

![Image](https://github.com/Altinn/app-frontend-react/assets/46874830/cf6a02c9-8578-499e-ae5c-1941df5574fc)

**Comment by olemartinorg** [comment] 2023-05-30 10:06
In a way, this is a duplicate of:
- #1105

**Closed** 2023-08-01 07:08 UTC
Labels: kind/feature-request, area/logic
