### ISSUE TITLE
Validating regex pattern on neighbouring property

### ISSUE THREAD

**Issue by jorgennyborgchr** [Altinn/app-frontend-react#939] opened 2023-02-17 12:02 UTC
### Description of the bug

```json
"organisasjon": {
      "type": "object",
      "properties": {
        "organisasjonsnummer": {
          "type": "string",
          "maxLength": 9,
          "minLength": 9,
          "pattern": "\\d{9}"
        },
        "organisasjonsnavn": {
          "type": "string",
          "maxLength": 1000
        }
      },
      "required": [
        "organisasjonsnummer",
        "organisasjonsnavn"
      ]
    },
```
![image](https://user-images.githubusercontent.com/124579304/219647985-1a46b85d-a99a-4dc2-816c-08104d2a05e1.png)

### Steps To Reproduce

1. Create two neighbouring properties as shown in the JSON-schema
2. Add regex validation to one of the fields
3. Fill in both fields and do not complete the regex validation, press "Submit", and you should  see the validation error on both fields.

**Comment by bjosttveit** [comment] 2023-03-27 12:10
Do you have a link to an app with this implemented?

**Comment by bjosttveit** [comment] 2023-08-07 07:33
@jorgennyborgchr I am not sure if I can reproduce this bug with the provided information. Do you have an app where this bug occurs?

If this issue is not relevant any more, please close this issue.

**Comment by olemartinorg** [comment] 2023-08-30 07:09
Closing this, as we're unable to reproduce.

**Closed by olemartinorg** 2023-08-30 07:09 UTC
Labels: kind/bug

**Comment by tjololo** [comment] 2023-08-30 07:11
Closing this as we cannot reproduce and no additional information is provided. 
Please reopen and supply with additional information if the issue is still relevant.
