### ISSUE TITLE
Frontend does not handle regex validation correct

### ISSUE THREAD

**Issue by hflateland** [Altinn/app-frontend-react#819] opened 2023-01-06 10:59 UTC
### Description of the bug

Tested on schema https://altinn.studio/repos/srf/melding-til-statsforvalteren

Field SaksID has regex [0-9]{5,6} in the XSD and a custom error message in the schema.json

`<xsd:simpleType name="saksId_Restriksjon">
    <xsd:restriction base="xsd:token">
      <xsd:pattern value="[0-9]{5,6}" />
    </xsd:restriction>`

`"Saksid": {
      "$ref": "#/$defs/saksId_Restriksjon",
      "@xsdStructure": "XmlSchemaSimpleTypeRestriction",
      "errorMessage": "Du har ikke tastet en gyldig saksID."
    }`

When entering letters instead of number the validation is correct and the custom error message is shown
![image (26)](https://user-images.githubusercontent.com/44457738/210998766-1f8a9a0b-ac59-4cb5-a6d6-8111111a5a95.png)

When entering too many numbers the validation does not trigger and no error is shown.
![image (27)](https://user-images.githubusercontent.com/44457738/210998913-8a6d5753-93be-4b1d-b1fe-9f55cdf58f4b.png)

When trying to send the schema the validation trigger, but missing the custom error message
![image (28)](https://user-images.githubusercontent.com/44457738/210999057-3b99f2d1-dc60-4b89-a1a4-d810c8627b05.png)

### Steps To Reproduce

-

### Additional Information

-

**Comment by bjosttveit** [comment] 2023-01-10 10:04
Closing as the regex was missing `^` and `$` and was not a bug in app-frontend.

Regex pattern should be changed to `^[0-9]{5,6}$`.

**Closed by bjosttveit** 2023-01-10 10:04 UTC
Labels: kind/bug, org/srf
