### ISSUE TITLE
RadioButtons isn't preselected with the data from the model

### ISSUE THREAD

**Issue by simendsjo** [Altinn/app-frontend-react#844] opened 2022-03-10 09:02 UTC
I have to set "preselecetedOptionsIndex" in addition to setting the model value in DataCreation. Only setting the value in the model, causes the radiobuttons to be unchecked.

**Comment by olemartinorg** [comment] 2023-02-08 15:18
From my understanding, that would also mean that setting a regular radio button and refreshing the page would render it unchecked (as in that case, we only have the value in the data model to point us in the right direction). I tested this on a radio group with `preselectedOptionsIndex` and were unable to reproduce the issue (the correct radio button, the one I chose before refreshing, gets checked).

Closing the issue as completed, but please re-open it with some steps to reproduce in case the problem persists.

**Closed by olemartinorg** 2023-02-08 15:18 UTC
Labels: kind/bug, org/krt
