### ISSUE TITLE
"Submit" button does not work

### ISSUE THREAD

**Issue by ivarne** [Altinn/app-frontend-react#706] opened 2022-12-01 13:32 UTC
### Description of the bug

In a few of our recently created apps, we have an issue with the "Submit" button failing without any visual clues. Reloading the page after filling out everything seems to fix the issue.

### Steps To Reproduce

1. Go to [krt.apps.tt02.altinn.no/krt/krt-1801a-1/](http://krt.apps.tt02.altinn.no/krt/krt-1801a-1/)
2. Fill out all required fields.
3. Click "Submit"
4. [Nothing happens]
5. Reload the page and click "Submit" again
6. [Opens receipt page]

### Additional Information

https://altinn.studio/repos/krt/krt-1801a-1

**Comment by bjosttveit** [comment] 2022-12-02 12:15
Duplicate of [#693](https://github.com/Altinn/app-frontend-react/issues/693). Confirmed that [#694](https://github.com/Altinn/app-frontend-react/pull/694) fixes this issue for this app.

**Closed by bjosttveit** 2022-12-02 12:15 UTC
Labels: kind/bug, org/krt

**Comment by bjosttveit** [comment] 2022-12-02 12:22
https://github.com/Altinn/app-frontend-react/pull/694 is now merged to main
