### ISSUE TITLE
Checkbox helptext icon placed wrong

### ISSUE THREAD

**Issue by hanneline** [Altinn/app-frontend-react#2001] opened 2024-03-22 07:20 UTC
### Description of the bug

The helptext icon for checkboxes shows up under the label, not at the end of the label as others do. 
![image](https://github.com/Altinn/altinn-studio/assets/47357434/5f9b318f-a386-4136-9169-cf2901857e56)

### Steps To Reproduce

1. Add a checkbox component to an app
2. Add helptext to the checkbox
3. Run the app

### Additional Information

Our app https://altinn.studio/repos/brg/aarsregnskap-ideelle-202402

**Comment by olemartinorg** [comment] 2024-04-11 05:34
Closing as duplicate of #1972 (fixed in #1975, released in [v4.2.0](https://github.com/Altinn/app-frontend-react/releases/tag/v4.2.0))

**Closed by olemartinorg** 2024-04-11 05:34 UTC
Labels: kind/bug
