### ISSUE TITLE
Add defaultValue option to variables in text

### ISSUE THREAD

**Issue by mikaelrss** [Altinn/app-frontend-react#1440] opened 2023-09-08 10:05 UTC
### Description

I would like there to be an option to set a default value in variables in text resources. This would allow us to provide sensible default whenever the data model returns a null value for a given path. 

### Additional Information

Related issue: #754. The issue that is reported here can be resolved by providing empty strings as default values.

**Comment by olemartinorg** [comment] 2023-09-11 07:26
Duplicate of #754?

**Closed** 2023-09-14 06:48 UTC
Labels: kind/feature-request
