### ISSUE TITLE
Mobile view for likert component does not work

### ISSUE THREAD

**Issue by nkylstad** [Altinn/app-frontend-react#216] opened 2022-06-08 06:51 UTC
## Description
In Likert component, PR#72. Screen size/mobile view. Looks like this is not working as expected. When the screen is small enough, the table view with rows and column headers disappears, but the question is still rendered as a table row, with radio buttons next to each other. 

## To Reproduce
1. Go to an app displaying the likert component
2. Reduce screen size until table view (column headers and borders) disappears
3. See error --> not displaying mobile view as per design outlined in #72

## Expected behavior
Expect radio buttons to display as column, with radio buttons below one another, with text at the top:
https://user-images.githubusercontent.com/43168787/169806593-7ef2bb6b-2322-46cd-a4ac-1a782f93b38d.png

## Screenshots
This is what it looks like when tested now:
![image](https://user-images.githubusercontent.com/1636323/172346621-7f04a2fa-c7c9-477b-817e-02f5c6ec3f9c.png)
![image](https://user-images.githubusercontent.com/1636323/172347423-61d6edd2-a4ac-4c94-994c-bc16f1da0d65.png)

## Additional info
- Tested in Chrome

**Comment by lasseklovstad** [comment] 2022-06-08 12:39
When trying to reproduce this bug I had to set `"layout": "table",` on the `Likert` component. I Wasn't able to reprduce it without setting layout explicitly in the layout file. How does your json layout look like?

**Comment by olemartinorg** [comment] 2022-07-01 08:01
I'm also not able to reproduce this unless overriding with `"layout": "table"`. Closing for now.

**Closed by olemartinorg** 2022-07-01 08:01 UTC
Labels: external-contribution-❤️, kind/bug, solution/app-frontend, org/udir, status/triage
