### ISSUE TITLE
Moving to a newer Date library since Moment Js is deprecated

### ISSUE THREAD

**Issue by Djuppi** [Altinn/app-frontend-react#1015] opened 2023-03-15 13:31 UTC
### Description

As it says in the title I would suggest migrating to a better supported date/time library for React like date-fns. Moment is deprecated from 2020 and will probably be less and less supported. I believe that this is used in altinn-frontend-react

**Comment by bjosttveit** [comment] 2023-03-22 14:47
Duplicate of: https://github.com/Altinn/app-frontend-react/issues/191

**Closed by bjosttveit** 2023-03-22 14:47 UTC
Labels: kind/feature-request
