### ISSUE TITLE
Validation not working

### ISSUE THREAD

**Issue by magnusrf** [Altinn/app-frontend-react#1498] opened 2023-09-25 11:19 UTC
### Description of the bug

We've had validation for 'Saksnummer' in our correspondence schema up until recently, it looks like at stopped working on release 3.66. All the other validations works, but for 'Saksnummer' it's not, it is the only input with 2 valdation attributes

### Steps To Reproduce

1. Go to https://altinn.studio/repos/pat/correspondence
2. Type in >20 characters and character not digit/letter for 'Saksnummer'
3. Validation not working

**Comment by olemartinorg** [comment] 2023-09-25 13:53
Hi! We fixed a problem where not  all validation messages showed up, which was released in [v3.67.0](https://github.com/Altinn/app-frontend-react/releases/tag/v3.67.0). Could you check and make sure the problem is still present in the latest version (currently v3.68.0)?

**Comment by magnusrf** [comment] 2023-09-25 14:07
Hi, we have the latest release, and tested it on tt02, also on different machines, still no better

**Comment by bjosttveit** [comment] 2023-09-26 08:06
This problem was introduced in version [v7.14.0](https://github.com/Altinn/app-lib-dotnet/releases/tag/v7.14.0) of the nuget packages, and was fixed by https://github.com/Altinn/app-lib-dotnet/pull/314. Please upgrade the nuget packages to version 7.15.1 when that gets released.

**Closed by bjosttveit** 2023-09-26 08:06 UTC
Labels: kind/bug
