### ISSUE TITLE
App crashes in repeating group when reference is selected in "Legg til ny referanse"

### ISSUE THREAD

**Issue by lassopicasso** [Altinn/app-frontend-react#1004] opened 2023-03-14 12:32 UTC
### Description of the bug

In repeating group, when a reference is selected, the app crashes. 
See video example below. Where I add inputs "Endre fra" and "Endre verdi til". Then I go to the add reference and try to select this as reference. App crashes with an error 400.

[![Logging]((https://user-images.githubusercontent.com/74791975/224999091-5b9a29b9-e724-46a3-ad2c-ca81882125b0.png)
)](https://user-images.githubusercontent.com/74791975/224998478-ec6fefce-4bf6-4852-af21-d6549a4a61fc.mp4)

### Steps To Reproduce

1. Run the [App-LocalTest repository](https://github.com/Altinn/app-localtest)
2. Go to the page "Repeating"
3. Try to add a new reference, and the app will crash with error 400.

**Comment by olemartinorg** [comment] 2023-03-15 08:21
Very related to, if not duplicate of:
- #985 

With regards to the crashing, that is fixed in a newer version of `frontend-test`, so pull from master. 😊

**Comment by lassopicasso** [comment] 2023-03-15 10:40
Closes this issue. It is fixed in a newer version of frontend-test. See comment above from Ole Martin.

**Closed** 2023-03-15 10:40 UTC
Labels: kind/bug, status/triage
