### ISSUE TITLE
New PDF enhancements

### ISSUE THREAD

**Issue by bjosttveit** [Altinn/app-frontend-react#896] opened 2023-02-06 12:15 UTC
### Description

During a discussion with Eirik, some points about enhancing the new PDF generator came up:

- [ ] Support grid layout (if chromium can handle the flex-layout)
- [x] More page-break options like `avoid` (maybe support the whole css spec instead of boolean like today)
  - [x] Also add support for page break in automatic layout
  - https://github.com/Altinn/app-frontend-react/pull/916
- [ ] Show components differently than in summary? (more compact?)

**Comment by RonnyB71** [comment] 2024-01-31 11:11
Closing this as a duplicate of https://github.com/Altinn/app-frontend-react/issues/1744

**Closed by RonnyB71** 2024-01-31 11:11 UTC
Labels: kind/feature-request
