### ISSUE TITLE
WCAG: Parsing errors in Altinn Apps

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#760] opened 2022-12-16 10:51 UTC
### Description of the bug

Using the [W3 validator](https://validator.w3.org/) I found two parsing errors. 
<img width="1518" alt="Skjermbilde 2022-12-16 kl  11 03 38" src="https://user-images.githubusercontent.com/33222679/208081932-88be3a82-bdcb-4331-b31f-898cc394a6d1.png">

This is a breach on [4.1.1. Parsing](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-parses.html)
- [ ] Use W3 validator on other apps to see if we have more parsing issues
- [ ] Fix all parsing issues

### Steps To Reproduce

Go to an app and run the validator and see the errors

This is a good way of running the validator and sorting out all errors using bookmarklet: https://www.tpgi.com/wcag-2-0-parsing-error-bookmarklet/

**Comment by bjosttveit** [comment] 2023-01-16 09:07
First error has been fixed in app-template, but will persist in old apps unless manually updated. https://github.com/Altinn/app-template-dotnet/pull/75

**Comment by bjosttveit** [comment] 2023-01-16 09:40
Not sure what caused the second error, it is probably not a universal issue as I could not reproduce this in my app,. It could be a problem with app-frontend that only appears in special cases,  which app were you using @Febakke ?

**Comment by bjosttveit** [comment] 2023-01-16 09:44
I get some different errors when I run my app through the same validator, and many of them are probably not important to fix.

**Comment by bjosttveit** [comment] 2023-01-16 10:26
I get the second error as well for my app, and it appears that the error message is a bit misleading. There is not a stray closing tag without a corresponding opening tag. What likely causes the issue is that (at least in my case) there is a `ul` element inside the `p` element. This is expected behavior from the app, as you can use markdown to format the content of our `Paragraph` component, but this is not allowed in html. React actually complains about this too.

![image](https://user-images.githubusercontent.com/47412359/212656135-adb381ee-a1e2-4028-9bfb-1f23ae9501ba.png)


The solution could be to change the element used in the paragraph component to a `div`.

**Closed** 2023-01-23 14:04 UTC
Labels: kind/bug, area/accessibility, status/triage
